// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Project: mykirana-b00e1  |  Project number: 663594485566
  // Package: com.vijaybore.mykirana
  // App ID (Android): 1:663594485566:android:7f02a2d1698c9cf5dc4e6f
  // API key matches google-services.json

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQtSE9Nc0vmDl8KzUG1ldr9lfL7DXWybg',
    appId: '1:663594485566:android:7f02a2d1698c9cf5dc4e6f',
    messagingSenderId: '663594485566',
    projectId: 'mykirana-b00e1',
    storageBucket: 'mykirana-b00e1.firebasestorage.app',
  );

  // Web / Windows / iOS / macOS use the same project.
  // Update these once you add those platforms in the Firebase console.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQtSE9Nc0vmDl8KzUG1ldr9lfL7DXWybg',
    appId: '1:663594485566:android:7f02a2d1698c9cf5dc4e6f',
    messagingSenderId: '663594485566',
    projectId: 'mykirana-b00e1',
    authDomain: 'mykirana-b00e1.firebaseapp.com',
    storageBucket: 'mykirana-b00e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQtSE9Nc0vmDl8KzUG1ldr9lfL7DXWybg',
    appId: '1:663594485566:android:7f02a2d1698c9cf5dc4e6f',
    messagingSenderId: '663594485566',
    projectId: 'mykirana-b00e1',
    storageBucket: 'mykirana-b00e1.firebasestorage.app',
    iosBundleId: 'com.vijaybore.mykirana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQtSE9Nc0vmDl8KzUG1ldr9lfL7DXWybg',
    appId: '1:663594485566:android:7f02a2d1698c9cf5dc4e6f',
    messagingSenderId: '663594485566',
    projectId: 'mykirana-b00e1',
    storageBucket: 'mykirana-b00e1.firebasestorage.app',
    iosBundleId: 'com.vijaybore.mykirana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQtSE9Nc0vmDl8KzUG1ldr9lfL7DXWybg',
    appId: '1:663594485566:android:7f02a2d1698c9cf5dc4e6f',
    messagingSenderId: '663594485566',
    projectId: 'mykirana-b00e1',
    authDomain: 'mykirana-b00e1.firebaseapp.com',
    storageBucket: 'mykirana-b00e1.firebasestorage.app',
  );
}
