// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF6-PFTKoJJvVi0tLi1qBWgqEp4fWZGd0',
    appId: '1:977188885752:web:9f42ad5768507a93d8570d',
    messagingSenderId: '977188885752',
    projectId: 'mykirana-1e888',
    authDomain: 'mykirana-1e888.firebaseapp.com',
    storageBucket: 'mykirana-1e888.firebasestorage.app',
    measurementId: 'G-FL0K9LVTE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvB0wN-FYoY_vc2PhM9uX_l6XadQ5R-rw',
    appId: '1:977188885752:android:bdc4fc8c22da13c7d8570d',
    messagingSenderId: '977188885752',
    projectId: 'mykirana-1e888',
    storageBucket: 'mykirana-1e888.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXYrg-AxPHcfHBa7LxvlS2FzZe9iy5beQ',
    appId: '1:977188885752:ios:125db6d1ac80156bd8570d',
    messagingSenderId: '977188885752',
    projectId: 'mykirana-1e888',
    storageBucket: 'mykirana-1e888.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXYrg-AxPHcfHBa7LxvlS2FzZe9iy5beQ',
    appId: '1:977188885752:ios:125db6d1ac80156bd8570d',
    messagingSenderId: '977188885752',
    projectId: 'mykirana-1e888',
    storageBucket: 'mykirana-1e888.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF6-PFTKoJJvVi0tLi1qBWgqEp4fWZGd0',
    appId: '1:977188885752:web:af5b8677bc4f0a90d8570d',
    messagingSenderId: '977188885752',
    projectId: 'mykirana-1e888',
    authDomain: 'mykirana-1e888.firebaseapp.com',
    storageBucket: 'mykirana-1e888.firebasestorage.app',
    measurementId: 'G-PJ88KSG9MW',
  );
}
